### ISSUE TITLE
Can't Fax outbound

### ISSUE THREAD

**Issue by JazMTaz** [DoubleBastionAdmin/pax-fax#2]
Nextcloud 25.0.4, PHP 8.1.17, app version 1.0.9

I can receive normally but outbound is no longer working and fails with a pop up error, however they show up in the folder as sent successfully. The popup message states;

Error ! Please check your settings !

**Comment by DoubleBastionAdmin** [comment]
We have just tested sending and receiving faxes with Nextcloud 25.0.4 and Pax Fax 1.0.9 and everything works.

We use the latest version of PHP for Debian, which is PHP 7.4.33. Have you upgraded your PHP version from 7 to 8 recently ?

Also, what errors do you see in your Nextcloud log when you try to send a fax ? Do you use Nginx or Apache ? Is your Nextcloud running directly on the server or inside a Docker container ?

**Comment by DoubleBastionAdmin** [comment]
Also, what MariaDB/MySQL version are you using ?

If you run:
```
php -i | grep mysqlnd
```
what is the version number of mysqlnd ?

And what operating system are you using ?

**Comment by DoubleBastionAdmin** [comment]
We detected some errors when removing the sent files from the `temp_files` directory in Nextcloud 25.0.4, although these errors didn't prevent faxes from being sent. Anyway, we made a few changes and published a new version of the app.

Please upgrade Pax Fax to version 1.1.0 and post here if you can send and receive faxes.

**Comment by JazMTaz** [comment]
Sorry for the delay. I updated the app from the NC app store and the issue is resolved for me, thank you so much, great application, great response, keep up the good work! To answer your previous questions, which are now moot I suppose, I am on PHP Version: 8.1.17 and MariaDB/MySQL Server version: 10.6.12-MariaDB-0ubuntu0.22.04.1 Ubuntu 22.04 Client API library version => mysqlnd 8.1.17mysqlndmysqlnd => enabledVersion => mysqlnd 8.1.17Loaded plugins => mysqlnd,debug_trace,auth_plugin_mysql_native_password,auth_plugin_mysql_clear_password,auth_plugin_caching_sha2_password,auth_plugin_sha256_passwordClient API version => mysqlnd 8.1.17 Sent from Mail for Windows From: DoubleBastionAdminSent: Wednesday, March 22, 2023 3:02 PMTo: DoubleBastionAdmin/pax-faxCc: JazMTaz; AuthorSubject: Re: [DoubleBastionAdmin/pax-fax] Can't Fax outbound (Issue #2) We detected some errors when removing the sent files from the temp_files directory in Nextcloud 25.0.4, although these errors didn't prevent faxes from being sent. Anyway, we made a few changes and published a new version of the app.Please upgrade Pax Fax to version 1.1.0 and post here if you can send and receive faxes.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by JazMTaz** [comment]
Issue resolved with app update, thanks so much!

**Comment by DoubleBastionAdmin** [comment]
Thank you very much for your appreciative words, for your rating on the app store and for your donation. We are glad that now Pax Fax works as expected with your setup. Please don't hesitate to post any issues or feature requests that you might have in the future.
